polyknoly/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('records/', include('records.urls')),
    path('admin/', admin.site.urls),
]

records/urls.py
from django.urls import path
from . import views

#add paths for url navigation 
app_name = 'records'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:candidate_id>/info/', views.candInfo, name='info'),
    path('<int:response_id>/results/', views.results, name='results'),
    path('input/', views.inputCand, name='input'),
    path('newData/', views.addData, name='addData')
]

records/models.py
from django.db import models
import datetime
from django.utils import timezone

from polyknoly.resources.staticStuff import POL_PARTY_CHOICES, ANSWERS

#Information/Resources

# https://docs.djangoproject.com/en/3.0/topics/db/
# https://docs.djangoproject.com/en/3.0/intro/tutorial04/
# Models and DB 

# 'blank' => determines if field is required in a form
    # True means its not required
    # False is required


# Create your models here.
class Candidate(models.Model):

    #Data
    # --------------------------------------------------------------- 
    fname = models.CharField(max_length=200, null=True, blank=True, verbose_name='First Name')
    lname = models.CharField(max_length=200, null=True, blank=False, verbose_name='Last Name')
    pol_office = models.CharField(max_length=200, null=True, blank=True, verbose_name='Political Office')
    pol_party = models.CharField(max_length=200, null=True, blank=True, choices=POL_PARTY_CHOICES, verbose_name="Political Party")
    link = models.CharField(max_length=200, null=True, blank=True, verbose_name='Link to Page')
    #image store binary data? bytes? need to look for more info
    #----------------------------------------------------------------
    #Methods
    def __str__(self):
        return "{1}, {0}".format(self.fname, self.lname)
         
    # --------------------------------------------------------------- 

class Question(models.Model):
    #Data
    # --------------------------------------------------------------- 
    question_text = models.CharField(max_length=200, verbose_name='Question')
    # --------------------------------------------------------------- 

    #Methods
    def __str__(self):
        return self.question_text
    # --------------------------------------------------------------- 

class Response(models.Model):

    #Data
    # --------------------------------------------------------------- 
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    response_text = models.CharField('response', max_length=200, blank=True, null=True)
    answer = models.CharField(max_length=5, null=True, blank=True, choices=ANSWERS)
    pub_date = models.DateTimeField(default=timezone.now, verbose_name='date published')
    # --------------------------------------------------------------- 

    #Methods
    def __str__(self):
        return self.response_text
    # --------------------------------------------------------------- 

records/forms.py
from django import forms

# test later
class CandForm(forms.Form):
    fName = forms.CharField(label= "First Name", max_length=100)

records/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect , Http404


from .models import Question, Candidate

# Create your views here.
#parameter argument 'request' => HttpRequest object
# https://docs.djangoproject.com/en/3.0/topics/forms/
def index(request):
    qlist = Question.objects.all()
    
    #output = ', '.join([q.question_text for q in qlist])

    #The context is a dictionary mapping template variable names to Python objects.
    context = {'question_list': qlist }
    return render(request, 'records/index.html', context)

    #return HttpResponse("have you ever voted and aked yourself: Who is this person? Or What is there stance on... ?")
    #return HttpResponse(output)

def candInfo(request, candidate_id):
    try:
        # calls model Manager to access the db
        candidate = Candidate.objects.get(pk=candidate_id)
        #response = "Viewing the candidate info for %s." % candidate_id
    except Candidate.DoesNotExist:
        raise Http404("Candidate does not exist in our database")

    #return HttpResponse(response)
    return  render(request, 'records/candidate.html', {'candidate': candidate})

def results(request, response_id):
    return HttpResponse("Viewing response %s." % response_id)

#def details(request):
    #return render(request, 'records/details.html')

def inputCand(request):
    return render(request, 'records/inCand.html')

# here we will add to db via save()
def addData(request):

    #In an HttpRequest object, the GET and POST attributes are instances of django.http.QueryDict,
        # a dictionary-like class customized to deal with multiple values for the same key. 
        # This is necessary because some HTML form elements, notably <select multiple>, pass multiple values for the same key.
        # The QueryDicts at request.POST and request.GET will be immutable when accessed in a normal request/response cycle.
        # To get a mutable version you need to use QueryDict.copy().
    if request.method == 'POST':
        q = request.POST
        print("Posted data....")
        print(q.items)

    return HttpResponse("<p>We got to addData</p>")

records/templates/records/candidate.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <title>Candidate Pages</title>
    <body>
        {% if candidate %}
            {{ candidate }}
        {% else %}
            <p>No candidate available...</p>
        {% endif %}
    </body>
</html>
    

records/templates/records/inCand.html
<!-- PURPOSE: Form to enter new Candidates to DB-->
<html>
    <head>
        <meta charset="utf-8">
    </head>

    <title> Input Data Page </title>
    <body>
        <div>
            <p>Temp element for now</p>
            <form action="{% url 'records:addData' %}" method="post">
            {% csrf_token %}
            
            <label for="fname">First Name:</label>
            <input type="text" name="fname" id="fname"><br><br>
            
            <label for="lname">Last Name:</label>
            <input type="text" name="lname" id="lname"><br><br>

            <label for="pOff">Political Office:</label>
            <input type="text" name="pOff" id="pOff"><br><br>

            <label for="pParty">Political Party:</label>
            <input type="text" name="pParty" id="pParty"><br><br>

            <input type="submit" value="Save">

            </form>

        </div>
    </body>
</html>

records/templates/records/index.html
<!DOCTYPE html>

<!-- TEMPLATES reference:
    https://docs.djangoproject.com/en/3.0/ref/templates/builtins/ 
-->

<html>
    <head>
        <meta charset="utf-8">
        <!-- CSS styling and links to source files can go here-->
    </head>

    <title>My Test Page</title>
    
    <body>

        <div>
            <!-- PAGE FUNCTION:
                    this page will list all questions and if a question is clicked it will send you
                    to a page for that question w/info 
                    
                    Sources: 
                        Illinois  
                            -> https://www.govtrack.us/congress/members/IL
                            -> https://ballotpedia.org/Illinois
                        Chicago
                            -> https://www.chicago.gov/city/en/chicagogovt.html
                            -> https://chicagoelections.gov/en/home.html
                            
            -->

            {% if latest_question_list %}
                <ul>
                    {% for question in latest_question_list %}
                        <li>
                            <!--<a href="/records/{{ question.id}}/">{{ question.question_text }}</a> -->
                            <a href="{% url 'records:index' question.id %}">{{ question.question_text }}</a>        
                        </li>
                    {% endfor %}    
                </ul>
            {% else %}
                <p>No records are available.</p>
                <a href="{% url 'records:input' %}">Add New Candidate </a>
            {% endif %}
        </div>
        
        
    </body>
    
</html>